Repository ethereum/staking-deposit-cli, pull requests merged in 2021-03, with the labels that each got.

#189 Prater Testnet Support
  README.md
  eth2deposit/settings.py
  setup.py
  tests/test_credentials.py
Labels: documentation, release

#190 Release v1.1.1
  README.md
  eth2deposit/credentials.py
  eth2deposit/key_handling/keystore.py
  eth2deposit/settings.py
  setup.py
  tests/test_cli/helpers.py
  tests/test_cli/test_existing_menmonic.py
  tests/test_cli/test_new_mnemonic.py
  tests/test_cli/test_regeneration.py
  tests/test_credentials.py
Labels: release

#195 Add Eth1 address withdrawal support
  README.md
  eth2deposit/cli/generate_keys.py
  eth2deposit/credentials.py
  eth2deposit/utils/constants.py
  eth2deposit/utils/validation.py
  tests/test_cli/test_existing_menmonic.py
  tests/test_cli/test_new_mnemonic.py
  tests/test_credentials.py
Labels: enhancement
