Repository ethereum/staking-deposit-cli, pull requests merged in 2022-02, with the labels that each got.

#235 Bump requirements_test.txt
  requirements_test.txt
  staking_deposit/utils/click.py
Labels: testing

#234 Murder "Eth2" in translations
  staking_deposit/intl/ar/cli/generate_keys.json
  staking_deposit/intl/el/cli/generate_keys.json
  staking_deposit/intl/fr/cli/generate_keys.json
  staking_deposit/intl/id/cli/generate_keys.json
  staking_deposit/intl/it/cli/generate_keys.json
  staking_deposit/intl/ja/cli/generate_keys.json
  staking_deposit/intl/ko/cli/generate_keys.json
  staking_deposit/intl/pt-BR/cli/generate_keys.json
  staking_deposit/intl/ro/cli/generate_keys.json
  staking_deposit/intl/zh-CN/cli/generate_keys.json
Labels: documentation

#230 Version bump v2.0.0.
  setup.py
Labels: release

#241 Bumps CLI_VERSION to 2.0.0
  staking_deposit/settings.py
Labels: release
